version: "3.4"

services:
  postgres:
    image: "postgres:14"
    container_name: tracker_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"
    volumes:
      - tracker_postgres:/var/lib/postgresql/data

volumes:
  tracker_postgres:
