# Examples of using Health API
# for vscode users, install `REST Client` to use these examples
# (for curl cli calls, see health.md)

@host = http://localhost:6000
@method = api/v1/health

# Health server check
GET {{host}}/{{method}}/

###

# DB connection check
GET {{host}}/{{method}}/readiness
